# Generated by Django 4.2.14 on 2024-11-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_player_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='opening',
            field=models.IntegerField(default=False),
        ),
    ]
