# Generated by Django 4.2.14 on 2024-11-23 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_opening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='opening',
        ),
    ]
